name: CI

on:
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      
      - name: Setup Java
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: "temurin"
        
      - name: Verify changes
        run: ./gradlew ktlintCheck

      - name: run tests
        run: ./gradlew test        
